# Generated by Django 4.1.7 on 2023-09-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('identificacion', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Identificacion')),
                ('nombre', models.CharField(max_length=50, verbose_name='Digite Nombre')),
                ('apellido', models.CharField(max_length=250, verbose_name='Digite Apellidos')),
                ('direccion', models.CharField(max_length=100, verbose_name='Digite Dirección de cliente')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Digite Teléfono de contacto')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('esFrecuente', models.BooleanField(default=False)),
                ('created_by', models.CharField(default='root', max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('NIT', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='NIT/C.C.')),
                ('razonSocial', models.CharField(error_messages={'unique': 'Ya existe esta empresa con otro NIT'}, max_length=50, unique=True, verbose_name='Nombre de Empresa o Proveedor')),
                ('direccionEmpresa', models.CharField(max_length=250, verbose_name='Dirección de contacto')),
                ('direccionVenta', models.CharField(blank=True, max_length=250, null=True, verbose_name='Dirección de punto de venta')),
                ('telefono', models.CharField(max_length=30, verbose_name='Telefono de contacto')),
                ('correo', models.CharField(blank=True, max_length=250, null=True, verbose_name='Correo electrónico de contacto')),
                ('created_by', models.CharField(default='root', max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
